# Developed by Mohammad Rameez Imdad (Rameez Scripts)
# WhatsApp: https://wa.me/923224083545 (For Custom Projects)
# YouTube: https://www.youtube.com/@rameezimdad (Subscribe for more!)

custom: ["https://wa.me/923224083545", "https://www.youtube.com/@rameezimdad"]
